<RootScreen>
    MDBottomNavigation:
    
        # Add a NavigationItem for each Navigation.
        MDBottomNavigationItem:
            name: "today screen"
            icon: "home"
            text: "Home"

            HomeScreen:

        
        MDBottomNavigationItem:
            name: "all exercises screen"
            icon: "information-outline"
            text: "About"

            

    
            # Add Contents here
            